import { Campaign } from "./types";

export const mockOverviewStats = {
  totalCampaigns: 500,
  smsCampaigns: 500,
  emailCampaigns: 5,
  whatsappCampaigns: 20,
};

export const mockCampaigns: Campaign[] = [
  {
    id: "CAMP-2025-001",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Delivered",
    messageContent:
      "Hello, please be reminded that PTA meeting holds tomorrow at 10:00 AM in the school hall. Kindly attend as important updates about academics and school activities will be discussed. Thank you.",
    intendedRecipients: 204,
    delivered: 230,
    failed: 10,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-002",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "Email",
    recipients: 202,
    status: "Failed",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 204,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-003",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-004",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-005",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-006",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-007",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-008",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-009",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-010",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-011",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "SMS",
    recipients: 202,
    status: "Scheduled",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: true,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
  {
    id: "CAMP-2025-012",
    title: "Lawanson",
    date: "30/08/2024",
    channel: "Whatsapp",
    recipients: 202,
    status: "Draft",
    messageContent: "Reminder for upcoming PTA meeting tomorrow.",
    intendedRecipients: 204,
    delivered: 0,
    failed: 0,
    createdDate: "18/05/2007",
    deliveryDate: "18/05/2007",
    createdBy: "Damilare John",
    lastUpdatedBy: "Damilare John",
    termAndSession: "24/25 Third Term",
    lastUpdated: "18/05/2007",
    paid: false,
    selectedRecipientsSummary: "2 Students, 2 Parents, 2 Tag Groups",
  },
];

export const getCampaignById = (id: string): Campaign | undefined => mockCampaigns.find(c => c.id === id) ?? mockCampaigns[0];

export const recipientOptions = [
  { value: "all-students", label: "All Students" },
  { value: "all-parents", label: "All Parents" },
  { value: "all-staff", label: "All Staff" },
  { value: "jss-1", label: "JSS 1 Students" },
  { value: "jss-2", label: "JSS 2 Students" },
  { value: "jss-3", label: "JSS 3 Students" },
  { value: "ss-1", label: "SS 1 Students" },
  { value: "ss-2", label: "SS 2 Students" },
  { value: "ss-3", label: "SS 3 Students" },
  { value: "pta-members", label: "PTA Members" },
];

export const channelOptions: { value: string; label: string }[] = [
  { value: "SMS", label: "SMS" },
  { value: "Email", label: "Email" },
  { value: "Whatsapp", label: "WhatsApp" },
];

export const RATE_PER_MESSAGE = 12;
